apiVersion: v1
kind: Secret
metadata:
  name: {{ template "osbpsql.fullname" . }}-auth
  labels:
    app: {{ template "osbpsql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  username: {{ b64enc .Values.basicAuth.username }}
  password: {{ b64enc .Values.basicAuth.password }}
