apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: test-postgresql-binding
  namespace: default
spec:
  instanceRef:
    name: test-postgresql
  secretName: test-postgresql-secret
