apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: test-postgresql
  namespace: default
spec:
  clusterServiceClassExternalName: postgresql
  clusterServicePlanExternalName: dummy
